### ISSUE TITLE
Demo版本2.0.0的源码

### ISSUE THREAD

**Issue by hishark** [easemob/videocall-android#13]
今天打开之前下载的Demo提示有更新，去官网安装最新的Demo之后想看看源码如何实现的，来这个库里看到版本还是1.4.1的，请问2.0.0版本的源码会上传吗？

**Comment by Lijian1122** [comment]
今天下午或者明早就会更新

**Comment by hishark** [comment]
好的~辛苦啦

**Comment by Lijian1122** [comment]
2.0.0源码已merge进去

**Comment by Lijian1122** [comment]
> 好的~辛苦啦

2.0.0源码已merge进去
